/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package de1;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.io.NotSerializableException;

/**
 *
 * @author ADMIN
 */
public class FormSV extends javax.swing.JFrame {

    /**
     * Creates new form FormSV
     */
    ArrayList<Student> danhSachSinhVien = new ArrayList<>();
    public FormSV() {
        initComponents();
        // Thêm sự kiện ActionListener cho nút "Thêm sinh viên"
        buttonthemsv.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Gọi phương thức xử lý khi nút "Thêm sinh viên" được click
                themSinhVien();
            }
        });
        // Thêm sự kiện ActionListener cho nút "Lưu"
        buttonluu.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Gọi phương thức xử lý khi nút "Lưu" được click
                luuDuLieuVaoTep();
            }
        });
    }
    private void themSinhVien() {
        // Lấy giá trị từ các trường nhập liệu trên giao diện
        String hoTen = texthoten.getText();
        int ngaySinh;
        try {
        ngaySinh = Integer.parseInt(textngaysinh.getText());
        } catch (NumberFormatException e) {
        // Xử lý nếu người dùng nhập không phải là số nguyên
        System.out.println("Ngay sinh khong hop le. Nhap so nguyen.");
        return; // Thoát phương thức nếu ngày sinh không hợp lệ
        }
        String diaChi = textdiachi.getText();
        String gioiTinh = buttonnam.isSelected() ? "Nam" : "Nu";
        String maSV = textmasv.getText();
        String eMail = textemail.getText();
        double diemTK;
        try {
        diemTK = Double.parseDouble(textdiemtk.getText());
        } catch (NumberFormatException e) {
        // Xử lý nếu người dùng nhập không phải là số thực
        System.out.println("Điem tong ket khong hop le. Nhap so thuc.");
        return; // Thoát phương thức nếu điểm tổng kết không hợp lệ
        }

        // Khởi tạo đối tượng sinh viên với các giá trị từ form người dùng nhập
        Student sinhVien=new Student(maSV,eMail,diemTK,hoTen,ngaySinh,diaChi,gioiTinh);
        // Hiển thị thông tin sinh viên lên màn hình console
        
        System.out.println("---Thong tin sinh vien---");
        sinhVien.display();
//        System.out.println("Họ tên: " + sinhVien.getHoten());
//        System.out.println("Ngày sinh: " + sinhVien.getNgaysinh());
//        System.out.println("Địa chỉ: " + sinhVien.getDiachi());
//        System.out.println("Giới tính: " + sinhVien.getGioitinh());
//        System.out.println("Mã sinh viên: " + sinhVien.getMasv());
//        System.out.println("Email: " + sinhVien.getEmail());
//        System.out.println("Điểm tổng kết: " + sinhVien.getDiemtk());
//        ArrayList<Student> danhSachSinhVien = new ArrayList<>();
        danhSachSinhVien.add(sinhVien);

    }


        // Phương thức để ghi dữ liệu vào tệp tin
    private void luuDuLieuVaoTep() {
        try {
            // Mở luồng đầu ra để ghi vào tệp sinhvien.dat
            FileOutputStream fileOut = new FileOutputStream("C:\\Users\\ADMIN\\OneDrive\\Documents\\NetBeansProjects\\test\\src\\de1\\sinhvien.dat");
            ObjectOutputStream objectOut = new ObjectOutputStream(fileOut);

            // Ghi danh sách sinh viên vào tệp tin
            objectOut.writeObject(danhSachSinhVien);

            // Đóng luồng
            objectOut.close();
            fileOut.close();

            System.out.println("Dữ liệu đã được ghi vào tệp sinhvien.dat");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        texthoten = new javax.swing.JTextField();
        textngaysinh = new javax.swing.JTextField();
        textdiachi = new javax.swing.JTextField();
        textmasv = new javax.swing.JTextField();
        textemail = new javax.swing.JTextField();
        textdiemtk = new javax.swing.JTextField();
        buttonthemsv = new javax.swing.JButton();
        buttonluu = new javax.swing.JButton();
        buttonnam = new javax.swing.JRadioButton();
        buttonnu = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ho ten:");

        jLabel2.setText("Ngay sinh:");

        jLabel3.setText("Dia chi:");

        jLabel4.setText("Gioi tinh:");

        jLabel5.setText("Ma sinh vien:");

        jLabel6.setText("Email:");

        jLabel7.setText("Diem tong ket:");

        textemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textemailActionPerformed(evt);
            }
        });

        textdiemtk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textdiemtkActionPerformed(evt);
            }
        });

        buttonthemsv.setText("Them sinh vien");

        buttonluu.setText("Luu");

        buttonnam.setText("nam");

        buttonnu.setText("nu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonthemsv)
                                .addGap(70, 70, 70)
                                .addComponent(buttonluu))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textdiemtk, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                                .addComponent(textemail)
                                .addComponent(texthoten)
                                .addComponent(textngaysinh)
                                .addComponent(textdiachi)
                                .addComponent(textmasv))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonnam, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(buttonnu, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(545, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(texthoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(buttonnam)
                    .addComponent(buttonnu))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textmasv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textdiemtk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonthemsv)
                    .addComponent(buttonluu))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textemailActionPerformed

    private void textdiemtkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textdiemtkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textdiemtkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonluu;
    private javax.swing.JRadioButton buttonnam;
    private javax.swing.JRadioButton buttonnu;
    private javax.swing.JButton buttonthemsv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField textdiachi;
    private javax.swing.JTextField textdiemtk;
    private javax.swing.JTextField textemail;
    private javax.swing.JTextField texthoten;
    private javax.swing.JTextField textmasv;
    private javax.swing.JTextField textngaysinh;
    // End of variables declaration//GEN-END:variables
}
